const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const { zodToJsonSchema } = require("zod-to-json-schema");
require("dotenv").config();
const puppeteer = require("puppeteer");

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

const interviewReportSchema = z.object({
  title: z.string(),

  matchScore: z.number().min(0).max(100),

  technicalQuestions: z.array(
    z.object({
      question: z.string(),
      intention: z.string(),
      answer: z.string(),
    })
  ),

  behaviouralQuestions: z.array(
    z.object({
      question: z.string(),
      intention: z.string(),
      answer: z.string(),
    })
  ),

  skillGaps: z.array(
    z.object({
      skill: z.string(),
      severity: z.enum(["low", "medium", "high"]),
    })
  ),

  preparationPlan: z.array(
    z.object({
      day: z.number(),
      focus: z.string(),
      tasks: z.array(z.string()),
    })
  ),
});

async function generateInterviewReport({
  resume = "",
  selfDescription = "",
  jobDescription = "",
}) {

  const prompt = `
You are an AI Interview Report Generator.

Generate a COMPLETE interview report in STRICT JSON format.

IMPORTANT RULES:
- Return ONLY valid JSON
- Do NOT use markdown
- Do NOT add explanations
- Do NOT add extra text
- Do NOT return arrays of strings
- Every array must contain OBJECTS
- Follow the exact structure

JSON STRUCTURE:

{
  "title": "Backend Developer",
  "matchScore": 85,

  "technicalQuestions": [
    {
      "question": "What is Node.js event loop?",
      "intention": "Check Node.js fundamentals",
      "answer": "Event loop handles async operations in Node.js."
    }
  ],

  "behaviouralQuestions": [
    {
      "question": "Tell me about a challenge you faced.",
      "intention": "Evaluate problem solving skills",
      "answer": "I solved API optimization issues."
    }
  ],

  "skillGaps": [
    {
      "skill": "Docker",
      "severity": "medium"
    }
  ],

  "preparationPlan": [
    {
      "day": 1,
      "focus": "Node.js Fundamentals",
      "tasks": [
        "Study event loop",
        "Practice async-await"
      ]
    }
  ]
}

Candidate Resume:
${resume}

Candidate Self Description:
${selfDescription}

Job Description:
${jobDescription}
`;

  try {

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        temperature: 0,
      },
    });

    const rawText = response.text;

    if (!rawText) {
      throw new Error("Empty response from Gemini");
    }

    const cleanedText = rawText
      .replace(/```json/g, "")
      .replace(/```/g, "")
      .trim();

    const parsedData = JSON.parse(cleanedText);

    const validatedData = interviewReportSchema.parse(parsedData);

    return validatedData;

  } catch (error) {

    console.error("Gemini AI service error:", error);

    throw new Error(
      `Error generating interview report: ${error.message}`
    );
  }
}

async function generateFromHtml(htmlContent) {
  const browser = await puppeteer.launch({
    headless: "new",
    args: [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-accelerated-2d-canvas",
      "--no-first-run",
      "--no-zygote",
      "--single-process"
    ],
  })
  const page = await browser.newPage()
  await page.setContent(htmlContent, { waitUntil: "networkidle0" })
  const pdfBuffer = await page.pdf({
    format: "A4",
    margin: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" },
  })
  await browser.close()
  return pdfBuffer
}

async function generateResumePdf({
  resume,
  selfDescription,
  jobDescription,
}) {

  const resumepdfSchema = z.object({
    html: z.string().describe(
      "Generated HTML content for resume which can be converted to PDF using puppeteer"
    ),
  })

  const prompt = `
Generate a professional resume in HTML format.

Resume:
${resume}

Self Description:
${selfDescription}

Job Description:
${jobDescription}

the response should be a JSON object with a single field "html" which contains the complete HTML content for the resume. Do not return any text other than the JSON response. Do not use markdown formatting. The HTML should be well-structured and suitable for conversion to PDF.
The resume should be tailored to the job description and should highlight the candidate's strengths and relevant experience. The HTML should be well-formatted and structured , making it easy to read and visually appealing.
THe content of the resume should be not stop like it's generated by AI and should be as close as possible to a real human-written resume.
you can highlight the content using some colors or different font styles but the overall design should be professional.
the content should be ATS friendly and should include relevant keywords from the job description.
The resume should be not be so long, it should ideally fit in 1-2 pages when converted to PDF. focus on quality rather than quantity. Do not add any explanations or extra text, return only the JSON response with the HTML content.
`

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        temperature: 0,
      },
    })

    const rawText = response.text?.trim()
    if (!rawText) {
      throw new Error("Empty response from Gemini resume generator")
    }

    const cleanedText = rawText
      .replace(/```json/g, "")
      .replace(/```/g, "")
      .trim()

    let jsonContent
    try {
      jsonContent = JSON.parse(cleanedText)
    } catch (parseErr) {
      const jsonMatch = cleanedText.match(/\{[\s\S]*\}$/)
      if (jsonMatch) {
        try {
          jsonContent = JSON.parse(jsonMatch[0])
        } catch (innerErr) {
          throw new Error(
            `Invalid JSON returned from resume generator: ${innerErr.message}. Raw output: ${cleanedText.substring(0, 500)}`
          )
        }
      } else {
        throw new Error(
          `Invalid JSON returned from resume generator: ${parseErr.message}. Raw output: ${cleanedText.substring(0, 500)}`
        )
      }
    }

    if (!jsonContent?.html) {
      throw new Error("Resume generator did not return an HTML field. Raw output: " + cleanedText.substring(0, 500))
    }

    const pdfBuffer = await generateFromHtml(jsonContent.html)

    return pdfBuffer
  } catch (error) {
    console.error("Resume PDF generation error:", error)
    throw new Error(`Resume PDF generation failed: ${error.message}`)
  }
}

module.exports = {
  generateInterviewReport,
  generateResumePdf
}