const express = require('express')
const authMiddleware = require("../middeleware/auth.middleware")
const interviewController = require("../controllers/interview.controller")
const interviewRouter = express.Router()
const upload = require("../middeleware/file.middleware")


/**
 * @route POST /api/interview/
 * @description generate new interview report on the basis of user self description,resume and job description
 * @access private
 */

interviewRouter.post("/", upload.single("resume"),authMiddleware.authUser, interviewController.generateIntrviewReportController)

/**
 * @route GET /api/interview/:interviewId
 * @description get interview report by id
 * @access private                                
 */
interviewRouter.get("/report/:interviewId", authMiddleware.authUser, interviewController.getInterviewReportByIdController)

/**
 * @route GET/api/interview/
 * @description get all interview report of logged in user
 * @access private
 */
interviewRouter.get("/", authMiddleware.authUser, interviewController.getAllInterviewReportController)

/**
 * @route GET/api/interview/resume/:interviewId
 * @description download resume pdf generated by ai for the interview report
 * @access private
 */
interviewRouter.post("/resume/pdf/:interviewId", authMiddleware.authUser, interviewController.generateResumeController)
 
 
 module.exports = interviewRouter;
